### ISSUE TITLE
Props and style

### ISSUE THREAD

**Issue by Merite15** [BayBreezy/nuxt-pdfmake#18]
Can i pass props and make my style with tailwind utilities classes

**Comment by BayBreezy** [comment]
Hello. I don't think that is possible. 
I have not seen where anyone has done that with the underlying pdf-make lib.

If you are using the tailwindcss-nuxt module, what I know you can do is import import your config like so
```ts
// Import fully resolved config
import tailwindConfig from '#tailwind-config'

// Import only part which is required to allow tree-shaking
import { theme } from '#tailwind-config'
```

And then use the values from your config to update the colors. You can check out the TW docs for that here: https://tailwindcss.nuxtjs.org/tailwind/config#referencing-in-the-application

**Comment by BayBreezy** [comment]
You can see it in action here on this implementation page: https://nuxt-pdfmake.behonbaker.com/examples/basic#implementation

The colors from tailwind is imported and used

**Comment by Merite15** [comment]
Thanks
