### ISSUE TITLE
Types are not defined. Unresolved function or method...

### ISSUE THREAD

**Issue by A1exZab** [BayBreezy/nuxt-pdfmake#4]
Hi there,

I'm trying to use your package with Nuxt 3.10.1 but stuck with following:
The module is installed according to the documentation and I can use the functionality of module, but there's something with types and $pdfMake is typed as any

Any insight into this? Am I doing something wrong?

Thanks for your package and any help.

![image](https://github.com/user-attachments/assets/e92d6145-5844-47f6-ae17-c0419854ee60)

**Comment by BayBreezy** [comment]
Hey @A1exZab I honestly struggle with this issue. sometimes it works and i get types.. sometimes it doesn't. I am gonna try making the types from pdfmake a dependency instead of a devDep and see if that works. Plus I need to update the documentation.

**Comment by A1exZab** [comment]
Got it, thanks for your reply.

Could you tell me if there is a way to fix this quickly? Maybe add some file in project with type/module declaration or something else (honestly, I’m not really good at it)?

**Comment by BayBreezy** [comment]
Hey @A1exZab ,
I just got the time to fix up this package. 
Try again and let me know if all is well with the types. I tried and it was working

**Comment by BayBreezy** [comment]
Hey @A1exZab , I am closing this as the types were added in a recent release.
Do let me know if you have any other problems.
